
mqtt_settings:
    pw: outsider
    user: outsider
    ip: "192.168.178.52"
    port: 1883
    node_id: smartscreen
    discovery_prefix: homeassistant
    operating_prefix: pydevice2mqtt


remote_devices:
  RPI_GPIO:
    - name: AutoButton
      object_id: autoexamplebutton
      component: binary_sensor
      pin: 11
    - name: AutoSwitch
      object_id: autoexampleswitch
      component: switch
      pin: 11

  RPI_RGB:
    - name: AlarmButton
      object_id: alarm_button
      component: light
      pin_r: 1
      pin_g: 2
      pin_b: 3