
mqtt_settings:
    pw: outsider
    user: outsider
    ip: "192.168.178.52"
    port: 1883
    node_id: PrintscanServer
    discovery_prefix: homeassistant
    operating_prefix: pydevice2mqtt
    logging: log


remote_devices:

#  SubprocessCall:
#    - name: Scanning
#      object_id: scanner
#      component: switch
#      exec_path: "E:\\Anwendungen\\Tools\\WinSCP\\WinSCP.exe"
#      arguments: null
#      looptime: 1

  RPI_GPIO:
    - name: SwitchState
      object_id: switch_state
      component: binary_sensor
      pin: 4
      inverted: true

  RPI_RGB:
    - name: SwitchLight2
      object_id: switch_ligth2
      component: light
      pin_r: 17
      pin_g: 22
      pin_b: 27
      active_high: true
      pwm_led: false

  ESpeakTTS:
    - name: TTSSpeaker
      object_id: tts_speaker
      component: tts
      voice: mb-de6
      rate: 120
      pitch: 40